### ISSUE TITLE
COM port error Windows 7 SP1 Pro (solved)

### ISSUE THREAD

**Issue by bvernoux** [joeqsmith/NanoVNA_Software#2]
I have a PC with Windows 7 SP1 Pro(with all updates) with a Nano VNA 2 Plus4
Note: I have also a HP 8753D 30kHz to 6GHz for accurate measurement full 2-ports with expensive calibration set...
For information my Computer + Nano VNA 2 Plus4 works perfectly when using the native application from https://nanorfe.com/nanovna-v2-software.html (https://nanorfe.com/downloads/NanoVNA-QT/20200507/vna_qt_windows.zip) so it is definitely not an issue with my computer/OS or Nano VNA 2 Plus 4 hardware.

I think it is interesting to create an issue even if it is solved now as it was very hard to understand what happened with some conflicts because of other version of LabView Runtime installed for other tools...

How I have reproduced the issue with your NanoVNA software v0.10:
I started with https://github.com/joeqsmith/NanoVNA_Software/releases/tag/0.10 which included all dependencies with an installer that I have installed in default path
When I try to connect on my Nano VNA 2 Plus 4 (on the right COM port) I always obtained an error -1073807342
See https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019NeQSAU&l=fr-FR which clearly does not help to solve that issue (except it is related to LabView NI-VISA issue ...).

- I have uninstalled everything related to LabView (as there was some VISA driver for other things which was probably in conflict) and reinstalled the NanoVNA software v0.10 with default path and that solved that issue

So this issue can be closed now (it is here to confirm that after a cleanup of previous LabView/LabView components install it works on Windows 7 SP1)

**Comment by joeqsmith** [comment]
Odd.  A few of us have used this installer without problems.   I have not used 7 for some time now but doubt that has anything to do with what you are seeing as I have ran this same version of LabView and VISA on XP.   Even your reinstall makes no sense.  I have various versions of LabView running on the same PC without any problems.   I would suggest trying to replicate the problem.  Then post the details on NI's site.  Maybe you found some case that they need to address.

**Comment by bvernoux** [comment]
Hi Joe,

> Odd. A few of us have used this installer without problems. I have not used 7 for some time now but doubt that has anything to do with what you are seeing as I have ran this same version of LabView and VISA on XP. Even your reinstall makes no sense. I have various versions of LabView running on the same PC without any problems. I would suggest trying to replicate the problem. Then post the details on NI's site. Maybe you found some case that they need to address.

I have wrote that issue to let know that users could have issues with LabView stuff because things are installed in system and are incompatible between version (it was my case as I have installed previous stuff requiring NI-VISA crap ...)
It is why I have create that issue to let know to users that if they have similar issue it is probably because they have previously installed LabView components (especially I suspect NI-VISA) which are incompatible even when we execute your setup which include everything (runtime ...).
To replicate the problem will be impossible in my case as I'm using this PC since more than 6 years for development and tons of things and of course I have installed/uninstalled tons of applications...
Anyway the solution was to remove everything related to LabView/NI (Including NI-VISA) to solve the issue then reinstall your setup.

> 
> "Note: I have also a HP 8753D 30kHz to 6GHz for accurate measurement full 2-ports with expensive calibration set..."
> I am trying to understand why you felt this comment was relevant. Anyone with funds can purchase any test equipment they like. Buying test equipment does not make you suddenly become an expert. Did you have software you wrote for it or something that you want us to look at? Myself, I have a few old VNAs. When I reviewed the V2Plus4, I showed a filter that I had characterized on my one old Agilent. This software actually runs on my other VNAs as well using Ethernet and GPIB.

I have added that note just to say that I'm using also other VNA and so it means I can do comparison with good old professional VNA up to 6GHz in doubt something is strange (in SW or HW) with the cheap Nano VNA V2 plus4.
I have developed my own Qt application (self contained/static build without external dependencies) to drive my old HP 8753D VNA (using USB to GPIB adapter) and retrieve S1P, Full S2P ... which I will probably publish on github one day (even if I doubt anyone care about those old VNAs except professionals ...).

**Comment by joeqsmith** [comment]
I have not used anything beyond LabView 2016 but am not seeing any incompatibility problems between versions.  I have run into problems with NI dropping support for hardware I use but that's a different issue.  It would have been good to know what the root problem was as it is rare I run into any problems with it.   Maybe there is an incompatibility problem with the later versions of LabView.   Again, a good question for NI if it comes up.

I don't know what a Qt application is but suspect it doesn't talk directly to the hardware with a protected OS and you just mean without any additional layers like VISA.  I am lazy which is why I use LabView and VISA.  I assume you only have problems with NI-VISA and not from other vendors, or just a general distain for LabView.      

I've seen people ask about software for the HP8753 series.   They are cheap enough now for many hobbyists.  One person posted about buying one to measure their antennas SWR.   I suspect your software would be welcomed by more than a few.    I don't have one, but would be interested in seeing what you came up with for it.  Maybe your GUI has some ideas I can leverage to improve my own software.

**Comment by bvernoux** [comment]
Yes my actual VNA Qt application (v0.2.3) is using VISA to communicate with GPIB from IVI Foundation\VISA\WinNT\lib\msc\visa32.lib or visa64.lib for Windows (32bits or 64bits)
In this version the GUI is quite basic (with some test buttons/code) as the aim is to retrieve S1P/S2P in different format
![image](https://user-images.githubusercontent.com/432709/114852105-c3517f80-9de2-11eb-8009-310f74efbbbe.png)

I'm already registered on https://groups.io/g/HP-Agilent-Keysight-equipment which is not very active ...

**Comment by joeqsmith** [comment]
From your original comment, "If you have a version without external dependencies it will be perfect",  it seems like its not so much having external dependencies you're concerned with but NI-VISA vs IVI Foundation's VISA.  

I have an old NI Ethernet GPIB controller that is no longer supported.  Sadly,  NI would not release documentation for it so I had to spend some time reverse engineering it.  So no more LabView GPIB library.  Instead I use the Ethernet library.   Prior to 2016, I would create a hardware interface in C.  Even then, the C would make calls to the OSs libraries.  So many layers.. So many dependencies...  

I didn't read through that whole thread on the Agilent groups but maybe your application is all they need.

**Comment by bvernoux** [comment]
I 100% agree on the fact GPIB to Ethernet is a must have to avoid those crappy VISA libraries/dependencies ...
I'm planning to buy a good GPIB to Ethernet adapter (as I have already lot of instruments in my lab using Ethernet only except the old gears with GPIB...) to replace my USB/GPIB converter and so add native Ethernet support which will do not requires VISA stuff ...
I will post the link on Agilent group when I will have released my VNA Qt HP 8753D code/app on github
So far it is not very clean code (with lot of test code to be removed ...)
- I was also planning to add SmithChart in it (as I have it in test in an other app) but I think we could live without SmithChart integrated as there is tons of good Apps to view s1p/s2p... files

**Comment by joeqsmith** [comment]
I have two of their first generation controllers that I bought when they first came out.  I still use NI-VISA to talk with them but the GPIB library is no more.
