### ISSUE TITLE
Installer zip files all have CRC error (no end of file).  

### ISSUE THREAD

**Issue by arhoufiry** [joeqsmith/NanoVNA_Software#4]
![image](https://user-images.githubusercontent.com/9158560/139440654-6fb947e9-cc58-45bd-a45b-58c8aa4ee0c8.png)

**Comment by joeqsmith** [comment]
I would start by asking yourself, what are the chances there is actually a problem with the ZIP files.   Then start with the README.  If you find reading is a problem for you, I wouldn't spend any more time on it.

**Comment by arhoufiry** [comment]
wow, what a jerk.  One would assume you live alone and vote democrat all
the way.  I would go all the way into saying you were the first in line to
get the vaxx shot.
Good luck with your crummy software, I hope you find a better use for your
life.

**Comment by arhoufiry** [comment]
You are just a jerk.  Either make your repo private, or get a better attitude.  Let's go Brandon!

**Comment by joeqsmith** [comment]
If you want to use the software you need to be able to read.  I'm fine with you taking offense to blunt honesty but it's really just that simple.

**Comment by a123dr** [comment]
I regret stumbling on this software.  I doubt you are the author, your iq
seems pretty deficient.
Please stop spamming me.

**Comment by joeqsmith** [comment]
No one is spamming you.  You have opted to receive emails from Github and continue with this discussion.   

>> I doubt you are the author, your iq seems pretty deficient.
That's "you're" not "your".

**Comment by a123dr** [comment]
This is fun.  Apparently, you're deficient in the language department
also.  I suggest you humble yourself and start treating others as you would
like to be treated.
I read through your responses to other cases and your attitude seems to
lack the human touch and willingness to help others.
I feel sorry for you.  Let's go Brandon!  Don't vote Democrat, they kill
your neurons!
