### ISSUE TITLE
dynamic graphic window size on NanoVNA_Software

### ISSUE THREAD

**Issue by ok1vaw** [joeqsmith/NanoVNA_Software#5]
Hello,
I use the main monitor with 2560x1600 resolution, when running the JoeSmith NanoVNA_Software, its window size is fixed (maybe about 1024x768) and could not be running full-screen. Is it an issue?

**Comment by joeqsmith** [comment]
It could very well be an issue for you but it is that is the way I designed it.  It poses no problems for me.   You're certainly not the first person who has asked.   

https://www.eevblog.com/forum/rf-microwave/nanovna-custom-software/
